---
title: "Ecological data management and analysis in R"
output: 
  ioslides_presentation:
    widescreen: true
    incremental: true
---

***
### Why use coding in R to manage and analyze ecological data? {.build}
<br>

- Code is **reproducible**. This means you can share it with your collaborators, reviewers, and other researchers and they will be able to see exactly what you did.  

- Code is **easily revised**. If you need to change an early step in your analysis pathway, it is generally efficient to make the change and re-run the rest of your analyses.  

- R is **open-source**. It's free to use, and its associated programs are free to use, so this means that you won't have to buy programs to analyse your data.  

- R has an **excellent support community**. If you run into a problem, it's highly likely that someone has already figured out the solution and put it online.


***
### Sounds great! Let's get started. {.build}
<br>  

- **Put the class project files onto your computer.**  

- **Open up RStudio.**  

- **Make an Rproject for this course.** File -> New project -> New directory -> Empty project

- Choose the directory that you'd like your project to be in and give your project a name. This will create a folder with your project file inside it.

- An Rproject is basically an organizer for a given project. When you open a project, you'll have easy access to the files associated with that project. **Put all the files I've given you into the folder associated with your Rproject.** 


***
### Now we need data. {.build}
<br>
Not just any data, but tidy data.



***
### What does tidy data look like? {.build}
<br>
  
- Each column contains one **variable** in a consistent format

- Each row contains one **observation**

- Each table/file contains one data set

- Column names are succinct (no spaces!), intuitive and have descriptive metadata associated with them in a separate file

- "Note" fields are useful and informative

- Data has been checked for typos

- For more on tidy data: http://vita.had.co.nz/papers/tidy-data.pdf

- Motivation: you'll need to produce tidy data for your final project

***
### Tidy data exercise {.build}
<br>
Example data source: Cameron EK, Cahill JF Jr, Bayne EM (2014) **Root foraging influences plant growth responses to earthworm foraging.** PLoS ONE 9(9): e108873.  

(The authors did a great job making their data tidy and accessible, but for learning purposes, I've messed it up a bit.)  
  
- Open up roots-messy.xlsx in Excel, Google Sheets, etc.

- Working in groups of 2-3, look at the data and identify issues that should be corrected before analysis.

- Then I'll demonstrate how to import a tidy data frame into R and check for any remaining problems.

***
### Time for some hands-on coding... {.build}
<br>

Open data-mgmt-student.R in RStudio.

Goals:  

- Get familiar with the RStudio interface
- Learn to write, run, and comment on code
- Learn to import and view data in R with <span style="color:magenta">read_csv</span>, <span style="color:magenta">head</span>, <span style="color:magenta">dim</span>, and <span style="color:magenta">summary</span>
- Learn some basic data manipulation (<span style="color:magenta">%>%</span>, <span style="color:magenta">filter</span>, <span style="color:magenta">group_by</span>, <span style="color:magenta">select</span>, and <span style="color:magenta">summarize</span>)
- Learn to visualize data by recreating plots from Cameron et al. with <span style="color:magenta">ggplot2</span>

***
### Datasheet design and data entry
<br>

- Datasheet design and data entry are best done in Excel, Google sheets, or a similar program.

- Datasheets should always contain a header with room for the date, the location, the experiment, and the names of the observers.

- Datasheets should be arranged intuitively to facilitate efficiency and minimize recording errors.

- Whenever appropriate, randomize your observations or experimental units. You can use random number generators for this.